account/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

from views import (login,
                   logout,
                   register,
                   send_mail,
                   activate,
                   test,
                   reset_password,
                   set_info,
                   find_password,
                   upload,
                   save_avatars,
                   avatars,
                  )


urlpatterns = patterns('',
     (r'^test/{0,1}$', test),
     (r'^login/{0,1}$', login),
     (r'^logout/{0,1}$', logout),
     (r'^register/{0,1}$', register),
     (r'^actmail/(?P<user_id>\d+)/{0,1}$', send_mail),
     (r'^activate/(?P<user_id>.*?)/(?P<code>.*)/{0,1}$', activate),
     (r'^reset/{0,1}$', reset_password),
     (r'^find-password/{0,1}$', find_password),
     (r'^upload/{0,1}$', upload),
     (r'^save_avatars/{0,1}$', save_avatars),
     (r'^avatars/{0,1}$', avatars),
     (r'^$', set_info),
)

invitation/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

from views import (send_invitation,
                   invite_register,
                  )


urlpatterns = patterns('',
     (r'^send$', send_invitation),
     (r'^invite/$', invite_register),
)

urls.py
# -*- coding:utf-8 -*-
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
import settings
from django.views.decorators.cache import cache_page
from django.views.static import serve as djangostatic
from appstore.views import view_rebang
#import django_cron
#django_cron.autodiscover()
urlpatterns = patterns('',
     (r'^admin/doc/', include('django.contrib.admindocs.urls')),
     (r'^admin/', include(admin.site.urls)),
     (r'^account$','account.views.set_info'),
     (r'^account/', include('account.urls')),
     (r'^invitation/', include('invitation.urls')),
     (r'^sitemap.xml$',include('appstore.sitemap')),
     #(r'^comment/',include('comments.urls')),
     (r'^$', 'appstore.views.view_index'),
     (r'^register/{0,1}$', 'account.views.register'),
     (r'^login/{0,1}$', 'account.views.login'),
     (r'^posturl/$','appstore.views.view_post_appurl'),
     (r'^top/{0,1}$','appstore.views.view_rebang'),
     #(r'^top/$',cache_page(view_rebang,60)),
     (r'^None/{0,1}$','appstore.views.view_redirect'),
     (r'^updatedb/{0,1}$','appstore.views.updatedb'),
     (r'^new/{0,1}','appstore.views.view_new_app'),
     (r'^app/(?P<item_id>\d{0,})/{0,1}$','appstore.views.view_item_detail'),
     (r'^app/(?P<item_id>\d{0,})/(?P<preference>.*?)/{0,1}$','appstore.views.view_app_like'),
     (r'^(?P<author_id>\d{0,})/(?P<preference>.*?)/applist/{0,1}$','appstore.views.view_user_likeapp'),
     (r'^user/\S{0,30}','appstore.views.view_user_home'),
     (r'^post/(?P<post_id>\d{0,})/{0,1}$','appstore.views.view_app_detail'),
     (r'^cron/{0,1}$','appstore.views.view_cron'),
     (r'^myshare/{0,1}','appstore.views.view_myshare'),
     (r'^(?P<author_id>\d{0,})/{0,1}$','appstore.views.view_myshare'),
     (r'^rate/(?P<flag>\S{0,4})/(?P<item_id>\d*?)/{0,1}$','appstore.views.view_post_rating_new'),
     (r'^check/(?P<flag>\S{0,4})/(?P<item_id>\d*?)/(?P<author_id>.*?)/{0,1}$','appstore.views.view_checklike'),
     (r'^del/comment/(?P<post_id>\d*?)/(?P<comment_id>\d*?)/(?P<page>\d{0,})','appstore.views.view_delete_comment'),
     #(r'^site_media/(?P<path>.*)$', cache_page(djangostatic,60*60*2),{'document_root': settings.STATIC_PATH},),
     (r'^site_media/(?P<path>.*)/{0,1}$', 'django.views.static.serve',{'document_root': settings.STATIC_PATH},),
     (r'^media/(?P<path>.*)/{0,1}$', 'django.views.static.serve', {'document_root': '/usr/local/lib/python2.6/dist-packages/django/contrib/admin/media/'}),
     (r'^static/(?P<path>.*)/{0,1}$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
)

account/models.py
#! /usr/bin/python
# -*- coding: utf-8 -*-

import os

from django.contrib.auth.models import User
from django.db import models
from django.conf import settings


class UserProfile(models.Model):

    id = models.AutoField('ID', primary_key=True)
    user = models.ForeignKey(User, verbose_name='关联用户', null=False, unique=True)
    nick_name = models.CharField('昵称', max_length=30, db_index=True)
    region = models.CharField('地区', null=True, max_length=100)
    register_datetime = models.DateTimeField('注册时间', auto_now_add=True)
    sex = models.BooleanField('性别', default=True)
    bio = models.TextField('简介', blank=True)

    @property
    def avatars(self):
        dirname_big = '%s/%s/%s/' % ('avatars', 'b', self.user.id % 100)
        dirname_small = '%s/%s/%s/' % ('avatars', 's', self.user.id % 100)
        dirname_huge = '%s/%s/%s/' % ('avatars', 'h', self.user.id % 100)
        filename_big = os.path.join(dirname_big, '%s.jpg' % self.user.id)
        filename_small = os.path.join(dirname_small, '%s.jpg' % self.user.id)
        filename_huge = os.path.join(dirname_huge, '%s.jpg' % self.user.id)
        if os.path.isfile(os.path.join(settings.MEDIA_ROOT, filename_big)):
            return filename_big, filename_small, filename_huge
        else:
            return 'avatars/default/avatar-big.png', 'avatars/default/avatar.png', ''

    class Meta:
        db_table = 'account_profile'

comment/models.py
# --*--coding:utf-8 --*--
from django.db import models
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from appstore.get_apple_appstore import do_encode
class post(models.Model):
    id=models.AutoField('ID',primary_key=True)
    author=models.ForeignKey(User,verbose_name=u"发布者") 
    content=models.TextField()
    goodrate=models.IntegerField(null=True)
    badrate=models.IntegerField(null=True)
    post_time=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return do_encode(self.id)
    def __unicode__(self):
        return do_encode(self.id)
    
class comment(models.Model):
    id=models.AutoField('ID',primary_key=True)
    author=models.ForeignKey(User,verbose_name=u"发布者") 
    post=models.ForeignKey(post,verbose_name=u"评论")
    content=models.TextField()
    goodrate=models.IntegerField(null=True)
    badrate=models.IntegerField(null=True)
    post_time=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return do_encode(self.id)
    def __unicode__(self):
        return do_encode(self.id)

invitation/models.py
#! /usr/bin/python
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models


class InviteCode(models.Model):
    '存放备选的邀请码'

    id = models.AutoField('流水号', primary_key=True)
    code = models.CharField('邀请码', max_length=10, db_index=True)


class InviteCounter(models.Model):
    '邀请码计数'

    id = models.AutoField('流水号', primary_key=True)
    user = models.ForeignKey(User, verbose_name='用户')
    code_counter = models.IntegerField('剩余邀请码数量')
    code_max = models.IntegerField('周期更新最大邀请码数量')


class Invitation(models.Model):
    '邀请的发送情况'

    id = models.AutoField('流水号', primary_key=True)
    user = models.ForeignKey(User, verbose_name='用户')
    code = models.CharField('邀请码', max_length=10, db_index=True)
    to_email = models.EmailField('被邀请Email', db_index=True)
    flag = models.IntegerField('code是否被使用')
    send_time = models.DateTimeField('发放邀请码时间', auto_now_add=True)

account/views.py
#! /usr/bin/python
# -*- coding: utf-8 -*-

import hashlib
import re
import os
import bsddb
import datetime
import uuid
import json
import traceback
import uuid

import PIL.Image

from django.contrib.auth.models import User
from django.contrib import auth
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.conf import settings
from django.core.mail import send_mail as django_send_mail
from django.contrib.auth.decorators import login_required


from account.models import UserProfile
from invitation.models import Invitation


def test(request):

    return render_to_response('account.html')



def login(request):
    '用户登陆, 要判断是否进行验证'

    if request.method != 'POST':
        return render_to_response('login.html', {'title': u'果味登陆'})

    #POST
    ######
    username = request.POST['email']
    password = request.POST['pwd1']

    user = auth.authenticate(username=username, password=password)
    if user is None:
        waring = {
            'main': u'验证失败',
            'details': u'邮件地址或密码错误',
            'helper': u'请重新',
            'url': '/account/login/',
            'url_text': u'登陆',
        }
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'登陆失败',})
    if not user.is_active:
        #未激活
        if not user.is_active:
            waring = {
                'main': u'用户未激活',
                'details': u'',
                'helper': u'',
                'url': '/account/actmail/%s/' % user.id,
                'url_text': u'重新发送激活邮件',
            }
            return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'用户未激活',},
                                      context_instance=RequestContext(request))

        user.login(request, -1 if is_keep else None)

    auth.login(request, user)

    return HttpResponseRedirect(request.GET.get('next', '/'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def register(request):
    '用户注册, 需要小心验证各字段值'

    if request.method != 'POST':
        code = request.GET.get('code', '')
        email = request.GET.get('email', '')
        return render_to_response('register.html', {'title': u'果味注册',
                                                   'code': code,
                                                   'email': email})

    invitation = request.POST['invitation']
    email = request.POST['email'].lower()
    password = request.POST['pwd1']
    password2 = request.POST['pwd2']
    nick_name = request.POST['nick_name']

    email_re = r'^[a-z0-9.+_-]+@[a-z0-9.-]{2,}\.[a-z]{2,}$'

    waring = {
        'main': u'注册失败',
        'details': u'',
        'helper': u'请重新',
        'url': '/account/register',
        'url_text': u'注册',
    }

    if re.match(email_re, email) is None:
        waring['details'] = u'Email地址不正确'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'注册失败',})

    if password != password2:
        waring['details'] = u'您输入的两次密码不相同'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'注册失败',})

    if len(password) < 5:
        waring['details'] = u'密码至少5个字符'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'注册失败',})

    if not 1 <= len(nick_name) <= 20:
        waring['details'] = u'您输入的昵称格式不正确'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'注册失败',})

    try:
        invitation_obj = Invitation.objects.get(code=invitation)
    except Invitation.DoesNotExist:
        waring['details'] = u'非法的验证码'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'注册失败',})
    else:
        if invitation_obj.flag == 1:
            waring['details'] = u'验证码已经被使用过了'
            return render_to_response('waring.html', {'waring': waring,
                                                         'title': u'注册失败',})

        if invitation_obj.to_email.lower() != email:
            waring['details'] = u'此邀请码不接受当前邮箱地址的注册'
            return render_to_response('waring.html', {'waring': waring,
                                                         'title': u'注册失败',})

    try:
        user = User.objects.create_user(username=email,
                                        email='',
                                        password=password,)

        invitation_obj = Invitation.objects.get(code=invitation)
        invitation_obj.to_email = email
        invitation_obj.save()
    except:
        waring['details'] = u'此 Email 已经被注册了'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'注册失败',})

    #注册成功直接变为登陆状态,不需要激活邮件了
    user.is_active = True
    user.save()

    profile = UserProfile(user=user)
    profile.nick_name = nick_name
    profile.save()

    invitation_obj.flag = 1
    invitation_obj.save()

    #登陆
    auth_user = auth.authenticate(username=email, password=password)
    auth.login(request, auth_user)

    return render_to_response('register_ok.html')
                                          


def send_mail(request, user_id):
    '给用户发激活信'

    user = User.objects.only('is_active', 'username').get(id=user_id)
    if user.is_active:
        raise Http404

    code = hashlib.md5(settings.SECRET_KEY + user_id).hexdigest()

    activate_url = 'http://guowee.com/account/activate/%s/%s/' % (user_id, code)
    email_content=settings.EMAIL_CONTEXT_ACTIVATION %(user.userprofile_set.all()[0].nick_name,activate_url)
    django_send_mail('请激活你的帐号，完成注册', email_content,
                     settings.DEFAULT_FROM_EMAIL, [user.username])

    return render_to_response('register_ok.html', {'title': u'果味网账号激活邮件'})


def activate(request, user_id, code):
    '激活账号'

    user = User.objects.only('username', 'is_active').get(id=user_id)
    right_code = hashlib.md5(settings.SECRET_KEY + user_id).hexdigest()
    if code == right_code and (not user.is_active):
        user.is_active = True
        user.save()
        waring = {
            'main': u'您的账号已经激活',
            'details': u'',
            'helper': '',
            'url': '',
            'url_text': '',
        }

        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'果味网账号激活',},
                                  context_instance=RequestContext(request))
    else:
        raise Http404


@login_required
def reset_password(request):
    '重置密码'

    if request.method != 'POST':
        return render_to_response('resetpassword.html', {'title': u'重置密码'},
                                  context_instance=RequestContext(request))

    old_password = request.POST['pwd3']
    password = request.POST['pwd1']
    password2 = request.POST['pwd2']

    waring = {
        'main': u'重置密码失败',
        'details': u'',
        'helper': u'',
        'url': '/account/reset',
        'url_text': u'再试一次',
    }

    if password != password2:
        waring['details'] = u'您输入的两次密码不相同'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'验证失败',},
                                  context_instance=RequestContext(request))

    if len(password) < 5:
        waring['details'] = u'密码至少5个字符'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'验证失败',},
                                  context_instance=RequestContext(request))

    if password == old_password:
        waring['details'] = u'新密码与旧密码相同, 不需要重置密码'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'验证失败',},
                                  context_instance=RequestContext(request))

    if not request.user.check_password(old_password):
        waring['details'] = u'原密码不正确'
        return render_to_response('waring.html', {'waring': waring,
                                                     'title': u'验证失败',},
                                  context_instance=RequestContext(request))
    else:
        request.user.set_password(password)
        request.user.save()
        #不用注销
        #auth.logout(request)
        return render_to_response('resetpassword_ok.html', {'title': u'重置密码成功',},
                                  context_instance=RequestContext(request))


def _save_avatar(user, file, type):
    '''保存某用户的头像
    根据用户的ID模100, 作一次目录hash.
    返回四个临时文件的路径位置.
    '''

    dirname = '%s/%s/%s/%s' % (settings.MEDIA_ROOT, 'avatars', type, user.id % 100)
    if not os.path.isdir(dirname):
        os.makedirs(dirname)

    file.open('r')
    image = PIL.Image.open(file)
    iw, ih = image.size
    if iw>ih:
        image=image.crop(((iw-ih)/2, 0, (iw-ih)/2+ih, ih))
    elif ih > iw:
        image=image.crop((0, (ih-iw)/2, iw, (ih-iw)/2+iw))
    else:
        pass
    origin = os.path.join(dirname, '%s.jpg' % uuid.uuid4().hex)
    image.save(origin)

    image.thumbnail((500, 500),PIL.Image.ANTIALIAS)
    huge = os.path.join(dirname, '%s.jpg' % uuid.uuid4().hex)
    image.save(huge)

    image.thumbnail((150, 150),PIL.Image.ANTIALIAS)
    big = os.path.join(dirname, '%s.jpg' % uuid.uuid4().hex)
    image.save(big)

    image.thumbnail((50, 50),PIL.Image.ANTIALIAS)
    small = os.path.join(dirname, '%s.jpg' % uuid.uuid4().hex)
    image.save(small)


    return (origin, huge, big, small)


def _script_str(status, msg, user_id, origin, huge, big, small):
    '返回给客户端的js执行段'
    s = '''

templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="sign_con">
    <h2>修改资料</h2>
     <div id="tip_layout">设置更新成功</div>
    <form id="form1" name="form1" method="post" action="." enctype="multipart/form-data"  onsubmit="return jQuery.formValidator.PageIsValid()">
      <p>
      <label>果味号：</label>{{ user.id }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/account/reset/">&gt;修改密码</a>
        </p>
      <p>
      <p>
        <label>昵称：</label>
        <input type="text" name="nick_name" id="nick_name" value="{{ nick_name }}" /></p>
      <p>
      <p>
        <label>头像：</label>
        <img src="/static/{{user.get_profile.avatars.0}}" width="100" height="100" />&nbsp;<label><a href="/account/avatars/">&gt;修改头像</a></label></p>
      <p>
        <label>自我介绍：</label>
        <textarea rows="3" name="bio" id="bio">{{ bio }}</textarea>
      </p>  
      <p class="btn"><br>
        <input type="button" name="button3" id="button3" onclick="postaccount()"  value="更新资料" />
      </p>
    </form>
  <script type="text/javascript">
	//处理提醒信息
	function postaccount(){
	postcont=$("#form1").serialize();
	$.ajax({
                    type: 'POST',
                    url: "/account/",
                    data: postcont,
                    dataType: "html",
                    success: function (data) {
							$("#tip_layout").slideDown(800);

													
							},});                    
                    }
	
</script>


{% endblock %}
{%block siderbar%}

  <p class="sign_tip">&gt;<a href="/invitation/send">邀请好友</a></p>

{%endblock%}   
</div>


templates/appdetail_5.html
{% extends "base.html" %}
{% block content %}
{% load get_rate %}  
  <div class="content"> 
    <!--开始-->
    <div class="app_detail">
      <div class="app_img"> <img src="{{data.artworkUrl100}}" width="160" height="160" />
        <p>[ iphone ]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="price">{{data.price_format}}</span></p>
      </div>
      <h1>{{data.name}}</h1>
      <dl class="app_info">
        <dt>大小：</dt>
        <dd>{{data.size}}</dd>
        <dt>分类：</dt>
        <dd>{{data.genre}}</dd>
        <dt>版本：</dt>
        <dd>{{data.vesion}}</dd>
        <dt>发布时间：</dt>
        <dd>{{data.releaseDate}}</dd>
        <dt>语言：</dt>
        <dd>{{data.languageCodesISO2A}}</dd>
        <dt>开发商：</dt>
        <dd>{{data.sellerName}}</dd>
        <dt>系统：</dt>
        <dd>{{data.app_requirements}}</dd>
        <dt>支持设备：</dt>
        <dd>{{data.device}}</dd>
      </dl>
      <div class="app_digg"><a href="#" class="bad">{{data.get_good_rate}}</a> <a href="#" class="good">{{data.get_bad_rate}}</a></div>
      <div class="app_des">
        <h2>屏幕截图 ·  ·  ·  ·  ·  · <a href="#">(全部6张)</a></h2>
        <div class="img_box"> 
        {%for img in data.iphone_screenshots%}

        <img src="{{img}}" />
        {%endfor%}
        {%for img in data.ipad_screenshots%}

        <img src="{{img}}" />
        {%endfor%}
        {%for img in data.mac_screenshots%}

        <img src="{{img}}" />
        {%endfor%}
        </div>
      </div>
      <div class="app_des">
        <h2>内容提要 ·  ·  ·  ·  ·  · </h2>
        {% autoescape off %}
        <div>{{data.description}}</div>
        {% endautoescape %}
      </div>
      
    </div>
    <!--结束-->
    <h2 class="title">最新评论 ·  ·  ·  ·  ·  · </h2>
    <div class="app_cont">
    {%for post in post_set%}
      <dl class="promulgator">
        <dt><img src="images/pic.jpg" /></dt>
        <dd class="share_man"><span><a href="/{{post.author.id}}/">{{post.author.get_profile.nick_name}}</a><em>{{ post.post_time|date:'Y-m-d H:i:s'}}&nbsp;&nbsp;推荐</em></span><span class="commet"><a href="/post/{{post.id}}/">&gt;{{post.get_comment_count}}回应</a></span></dd>
        <dd>{{post.content}}</dd>
      </dl>
      <div class="comment_dis">
        {% for comment in post.comments_set|order_data %}
    	<dl>
      	<dt><a href="/{{comment.author.id}}"><img src="/static/{{comment.author.get_profile.avatars.0}}"  width="25px" height="25px"></a></dt>
      	<dd class="person"><a href="/{{comment.author.id}}">{{ comment.author.get_profile.nick_name }}</a>{{ comment.post_time|date:'Y-m-d H:i:s'}}</dd>
      	<dd class="remark">{{ comment.content }}</dd>
    	</dl>
    	{% endfor %}
    	</div>
      {% endfor %}
      
    </div>
	<div class="pagenavigation">	
        {%for page in show_page.bodylist %}
			<a href="/?page={{page}}" class="{%ifequal page show_page.currect%}current{%endifequal%}">{{page}}</a>
			{%ifequal page show_page.startelpage%}...{%endifequal%}	
			{%ifequal page show_page.endelpage%}...{%endifequal%}		  
		  {%endfor%}							   
		  
	</div>
  </div>
  <div class="content_right">
  	<div>
      <h3>&gt;喜欢这个app的成员...<a href="/app/{{ data.id }}/like">(全部{{ data.get_like_count }}人)</a></h3>
      <ul class="member_list">
      {%for like in data.get_people_like|slice:":12" %}
        <li><a href="/{{ like.author.id }}"><img src="/static/{{like.author.get_profile.avatars.1}}"></a><a href="/{{ like.author.id  }}/">{{like.author.get_profile.nick_name}}</a></li>
      {%endfor%}
      </ul>
      <h3>&gt;不太喜欢这个app的成员...<a href="/app/{{data.id}}/unlike">(全部{{data.get_hate_count}}人)</a></h3>
      </ul>    
    </div>
  </div>
	{%endblock%}


templates/appshow.html
{% extends "base.html" %}
{% block content %}
<div class="join">
      <p> 从30万个app发现和分享你最喜爱的Ta<br />
        现在就加入我们！<br />
        <a href="/account/register">快速注册</a> </p>
    </div>
    {% for app in appdata %}
    <div class="app_cont">
      <p><span>{{ app.author.first_name }}</span>2010-01-15&nbsp;&nbsp;16:48&nbsp;&nbsp;推荐</p>
      <div class="app_show">
        <table id="digg" class="digg">
          <tr>
            <td width="14%" rowspan="2"><img src="{{ app.img_url}}" width="70px" height="70px"></td>
            <td width="25%"><h2>{{ app.name }}</h2></td>
            <td width="21%">{{ app.size }}</td>
            <td width="21%">价格：{{ app.price }}</td>
            <td width="19%">分类：{{ app.genre }}</td>
          </tr>
          <tr>
            <td><a href="{{ app.app_url }}" class="download">下载</a></td>
            <td><a href="#" class="good">0</a></td>
            <td><a href="#" class="bad">0</a></td>
            <td><a href="#" class="comment_amount">15</a></td>
          </tr>
        </table>
      </div>
      
      <div class="comment_dis">
      {% for comment in app.app_commten %}
        <dl>
          <dt><img src="images/pic.jpg"></dt>
          <dd class="person"><span>{{ comment.author.first_name }}</span>2010-01-15&nbsp;&nbsp;16:48</dd>
          <dd class="remark">{{ comment.content }}</dd>
        </dl>
        {% endfor %}
        <p class="more"><a href="#">更多评论>></a></p>
      </div>   
    <div class="app_more"><a href="#">查看更多</a></div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{{ title }}</title>
<meta name="keywords" content="{{keywords}}">
<meta name="description" content="{{description}}">
{% load cache %}
{% cache 500 base_hearder %}
<link type="text/css" rel="stylesheet" href="/site_media/css/reset.css" />
<link type="text/css" rel="stylesheet" href="/site_media/css/skin.css" />
<link rel="shortcut icon" href="/site_media/images/guo.ico" type="image/x-icon" />
<script src="/site_media/js/jquery-1.4.4.min.js" type="text/javascript"></script>
<script src="/site_media/js/formValidator.js" type="text/javascript"></script>
<script src="/site_media/js/formValidatorRegex.js" type="text/javascript"></script>
<script src="/site_media/js/sign.js" type="text/javascript"></script>
<script src="/site_media/js/home.js" type="text/javascript"></script>
<script src="/site_media/js/account.js" type="text/javascript"></script>
<script src="/site_media/js/resetpassword.js" type="text/javascript"></script>
<!--跟踪代码-->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-13254122-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
{% endcache %}
</head>

<body>
<div id="head">
  <h1 class="logo"><a href="/">guowee--快速分享和交流iPhone,iPad游戏和应用软件的小众社区</a></h1>
  {% if user.is_authenticated %}
    <span> <a href="/account">{{user.get_profile.nick_name}}的帐号</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/account/logout">退出</a></span>
  {% else %}
  <span><a href="/account/register">快速注册</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/account/login">登录</a></span>
  {% endif %}
  <div class="navigation"><a href="/" class="{{index_page}}">首页</a><a href="/{{user.id}}" class="{{user_page}}">我的果味</a><a href="/top" class="{{top_page}}">热榜</a>
    <div class="search">
      <form>
        <input type="text" class="text">
        <input type="submit" value="搜 索" class="btn">
      </form>
    </div>
  </div>
</div>
<div id="main">

{% block content %}

{% endblock%}
</div>
{% block siderbar%}
{% endblock %}
</div>
<div id="foot">
  <p class="link_ft"><a href="#"  target="_blank" >关于网站</a> <a href="#"  target="_blank">联系我们</a> <a href="#"  target="_blank">帮助</a></p>
  <p>copyright@2011 guowee.com</p>
</div>
</body>
</html>